### PR TITLE
just fixed some stuffs

### PR DESCRIPTION
**Pull request by Super-Baleine**
btw, using chattr is that useful? No need to install new programs on the machine, it's too invasive. Well, do whatever you want to, feel free to close :)

Signed-off-by: Paul Feuvraux <paul@muonium.ee>

### CODE REVIEW

**Comment by angristan** [comment]
Already fixed

**Comment by Super-Baleine** [comment]
Not the debian script...
https://github.com/Angristan/Local-DNS-resolver/blob/master/debian-unbound.sh#L24

**Comment by angristan** [comment]
There is nothing to fix in the Debian script

**Comment by Super-Baleine** [comment]
capture du 2017-08-07 15-52-59

**Comment by angristan** [comment]
What's wrong ? 🤔

**Comment by Super-Baleine** [comment]
```shell
echo "test \"test\""
```

In your code, the echo command is stopped at 'root-hints:"'

I suggest you to use echo 'blah' instead of echo "blah", it's easier to write when you don't need any variable. :)

**Comment by Super-Baleine** [comment]
It's more a suggestion actually, to have a better view on the code

**Comment by angristan** [comment]
I agree with your suggestion but the echo command is working well here :)

**Comment by Super-Baleine** [comment]
you didn't want to output this? :

root-hints: "/blah/" ?

if so, then you need to do \" in the /var part

Well, anyway, I mustn't have been clear enough :)

**Comment by angristan** [comment]
Oh, the double quotes were not echo'ed tough. They are not useful so it's not an issue but I'm gonna clean that

**Comment by Super-Baleine** [comment]
Well, yea, I wasn't clear enough, my bad

**Comment by angristan** [comment]
Yeah I see, `root-hints: "/var/lib/unbound/root.hints"` and `root-hints: /var/lib/unbound/root.hints` have the same effect, so it's not an actual issue :p

**Comment by angristan** [comment]
No problem, thanks

**Comment by Super-Baleine** [comment]
Good then, have a nice day

**Pull request closed without merging**
