### PR TITLE
Add "Check for DNS leaks" paragraph in README

### PR DESCRIPTION
**Pull request by UnixJunkie**

### CODE REVIEW

**Comment by cezar97** [comment]
Instead of Firefox it could just be check / visit this site.

**Comment by UnixJunkie** [comment]
you can edit the PR as you see fit.

**Comment by UnixJunkie** [comment]
Or, if there is a command to say, browse this URL with whatever browser you want to use.
But, honestly, firefox is a good choice I think.

**Comment by cezar97** [comment]
I agree, but I meant that there are also other browsers' users.

**Comment by UnixJunkie** [comment]
Please, don't leave my PRs rotting away.
Read them, then take what you like/want and merge them or close them.
If I see a project is well managed, I am more likely to contribute again in the future.
Thanks!

**Comment by cezar97** [comment]
Oh, it doesn't depends on me:smiley:.

**Comment by cezar97** [comment]
@Angristan what about adding this to the openvpn repo, too? https://github.com/Angristan/OpenVPN-install/issues/149

**Comment by angristan** [comment]
Good idea

**Pull request merged**
